name: Code quality

on:
  pull_request:

env:
  BIOME_VERSION: 1.9.3

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: ${{ env.BIOME_VERSION }}

      - name: Run Biome
        run: biome ci . --config-path=biome.json
